### ISSUE TITLE
Add auto-complete and typing support for paths, payloads and return types

### ISSUE THREAD

**Issue by davestewart** [davestewart/extension-bus#5]
## Background

Whilst sending messages via `string` channels works, neither the channel, payload or return data is typed.

What would be cool would be a way to have the code written for handlers be "fed back" into the host project's type system by way of augmentation, so that `bus.call(...)` would autocomplete and provide type safety.

## Research

It seems that manually augmenting `Bus::call()` _does_ produce the desired outcome:

![image](https://github.com/davestewart/extension-bus/assets/132681/26ff7650-bfed-41fd-a97f-12898288f1d4)

Example code:

```ts
// bus.t.ds
import { Window } from '@/api/windows'
import { Tab } from '@/api/tabs'

interface Config {
  'foo/bar': (value: number) => Promise<Window>;
  'foo/baz': (value: { id: number }) => Promise<Tab>;
}

declare module 'extension-bus' {
  interface Bus {
    call<Path extends keyof Config>(path: Path, ...args: Parameters<Config[Path]>): ReturnType<Config[Path]>;
  }
}
```
```ts
// use-bus.ts
import { type Bus, makeBus } from 'extension-bus'

const bus: Bus = makeBus('content', {
  handlers: {},
})

const result = bus.call('foo/baz', { id: 123 }).then(tab => {
  tab...
})
```
See:

- https://chat.openai.com/share/d1560171-e884-4d2b-946f-7f75f72dc4cc

The next stage would be to automate the creation of a `.dt.s` file in a host project with some kind of build tool.

I've done a small amount of AST work with [Alias HQ](https://github.com/davestewart/alias-hq/), so suspect it's within reach.

### Approach

An initial approach would be to build some rough code that walks a dummy handler file, and outputs a `d.ts` file.

Once that is up and running, the next stage would be to begin in files which use `makeBus()` and work backwards from the `options` object.

Another option would be to find all usage of the `Handlers` type, and process those files / entries.

Critically, handlers are scoped via the `source` property of `makeBus()` so potentially two sets of paths would need to be made; scoped and unscoped:

```ts
interface Config {
  'foo/bar': (value: number) => Promise<Window>;
  'background:foo/bar': (value: number) => Promise<Window>;
 }
```

Alternatively, conditional types could be used to enforce paths based on an instance's `target` property:

```ts
// Bus.d.ts
declare class Bus<T extends string> {
  target: T;
  call(path: T extends 'content' ? 'foo/bar' : 'one/two'): void;
}

export = Bus;
```

See:

- [Chat GPT](https://chat.openai.com/share/56de4206-d45a-4a77-98c5-7c4518e63bda)
- [TS Playground](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBCCuEA8AVaBTAHgF3QOwBMYJsAnASzwHMA+aAbwChppsxSr1sAuaFAbkbNowAPZ4SpeMGyjSACjYcuvFAEoGwltgAW5CADolnbNAC8rdicEsAvkJbAwIEPIAOYXaow58RaADkAGaioihWXAHQAPyBIaIAws4gUbwBAEZgAF5JLgFqvABuouQEmiwsAPSV0ACSALZuIOj1+GzY5OLQOuik6ML29ozV0ACqEGCcjGISpvEIMBZ46ADucIhIwaHhytgBNPJbYRF7aoLziAZOLofxuSln0CMA8gDSjBeG164Z2ff5-CeNQAoqRSHJeABBDjwVp4UyiIKsACebnQgQARJkcskMVF9NA8KJTJAIOQqHgwOlmqxRNAPKQwK1cKRoIiUWjMXdcQEhDMSNBsQtzITVutkL8sjsTPtDtjpZEzowhZdvnK-skAUDoG9ldkFldkrdQv9HiNQeDSFCYXCEUjsKj0QEMdyXHjoASiSSoOTKdT0bJ6ewmVxemz7Y7Mdj7njGEA)

There is also the consideration for content scripts:

```ts
declare module 'extension-bus' {
  interface Bus {
    call<Path extends keyof Config>(tabId: number, path: Path, ...args: Parameters<Config[Path]>): ReturnType<Config[Path]>;
    // overload here
  }
}
```

Finally, some kind of CLI tool would be required, with options or config such as output location, such as:

```json
{
  "scripts": {
    "extension-bus": "extension-bus build --watch --output .src/types/bus.d.ts"
  }
}
```

### Tasks

CLI:

- [ ] config / args
- [ ] watch
- [ ] run code

Parsing:

- [ ] choose AST lib
- [ ] parse basic handlers file
- [ ] extract paths, payloads, return types and imports
- [ ] write dummy `.d.ts` file

Dependencies:

- [ ] entry-point discovery for `makeBus()` and `:Handlers`
- [ ] walk dependencies and extract source scopes
- [ ] combine and build correct `.d.ts` output

## Notes

Packages:

- https://ts-morph.com/navigation/
- https://github.com/qwerqy/scan-imports
